# Generated by Django 3.2.13 on 2022-10-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=200)),
                ('portal_slug', models.CharField(max_length=20)),
                ('portal_url', models.URLField()),
                ('portal_publisher', models.CharField(blank=True, default='', max_length=200)),
                ('portal_director', models.CharField(blank=True, default='', max_length=200)),
                ('portal_editor_in_chief', models.CharField(blank=True, default='', max_length=200)),
                ('portal_about_us', models.TextField()),
                ('portal_logo', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Portals',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_subtitle', models.CharField(max_length=200)),
                ('article_category', models.CharField(max_length=200)),
                ('article_release_date', models.CharField(max_length=200)),
                ('article_shares_no', models.CharField(max_length=200)),
                ('article_comments_no', models.CharField(max_length=200)),
                ('article_url', models.URLField()),
                ('article_content', models.TextField(blank=True, default='')),
                ('article_sentiment_bow', models.CharField(blank=True, default='', max_length=200)),
                ('article_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.portal')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
