# Generated by Django 3.2.13 on 2022-11-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_comment_sentiment_bow'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content_lead',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
