# Generated by Django 3.2.13 on 2022-11-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_article_number_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_comments_no',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_shares_no',
        ),
    ]
