# Generated by Django 3.2.13 on 2022-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_release_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=255),
        ),
    ]
